### ISSUE TITLE
bug提交

### ISSUE THREAD

**Issue by xizhang523** [Mooooooon/TiezhuToolbox#1]
[console.log](https://github.com/Mooooooon/TiezhuToolbox/files/13778535/console.log)
大佬，我是逍遥模拟器，链接adb，初始化之后就没有反应了。点击截图那个按钮也没用。
![这个样子](https://github.com/Mooooooon/TiezhuToolbox/assets/103020119/89a1e257-dd97-40f5-b03d-dfa66e9e6068)

**Comment by Mooooooon** [comment]
不是程序本身的问题，可能是你电脑上运行了其他低版本的adb（可能是手机助手之类的）或者模拟器版本问题
有没有试过其他模拟器？

**Comment by xizhang523** [comment]
今天又试了试，可以用了，笑哭。
那天又试了mumu模拟器也是不行，就放弃了，还得是重启。
谢谢大佬的程序了，萌新就缺这玩意。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Mooooooon/TiezhuToolbox"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月2日(星期二) 晚上8:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Mooooooon/TiezhuToolbox] bug提交 (Issue #1)





 
不是程序本身的问题，可能是你电脑上运行了其他低版本的adb（可能是手机助手之类的）或者模拟器版本问题
 有没有试过其他模拟器？
