### ISSUE TITLE
部分装备显示bug

### ISSUE THREAD

**Issue by 10MillionTones** [Mooooooon/TiezhuToolbox#2]
某件夹攻套
![image](https://github.com/Mooooooon/TiezhuToolbox/assets/77432137/d3abab01-c83b-4e57-951e-86b23cd7abd9)
某件愤怒套
![image](https://github.com/Mooooooon/TiezhuToolbox/assets/77432137/4d19bd6b-8b13-40f2-9402-201b7796c3a6)
某件爆伤套：
![image](https://github.com/Mooooooon/TiezhuToolbox/assets/77432137/297e6162-27f3-459a-ac7a-7067371de38d)
某件激流套：
![image](https://github.com/Mooooooon/TiezhuToolbox/assets/77432137/52cc7add-9391-4ac8-a3bd-84018147cb60)

试了一下，大概是因为装备图标的变化导致的，出bug的都是各式各样的活动送的，具有不同的图标。
最新的这件是：
![image](https://github.com/Mooooooon/TiezhuToolbox/assets/77432137/26e5ffe5-f7ab-4a19-b4ea-819012309704)

题主可以考虑一下读装备上的文字，如：
![image](https://github.com/Mooooooon/TiezhuToolbox/assets/77432137/e05c2fd8-ec43-4f07-8e16-4862d078ce71)
![image](https://github.com/Mooooooon/TiezhuToolbox/assets/77432137/a0431277-5064-4155-84f9-11d0cad5e0fe)
![image](https://github.com/Mooooooon/TiezhuToolbox/assets/77432137/eb31a650-e317-4be1-9d74-fcd64ac4f967)
可以看出位置是一样的
希望对你有所帮助。

**Comment by Mooooooon** [comment]
没能复现🤔装备获取就是读取文字的，为了不让图标图标影响结果我都是涂黑的，可以在程序运行时侯查看temp文件夹看到（程序关闭后删除）
有条件可以提供一下temp文件我多测试一下

**Comment by 10MillionTones** [comment]
换了个模拟器，mumu12，还是会出现这样的问题。
![image](https://github.com/Mooooooon/TiezhuToolbox/assets/77432137/ea96b0d3-674e-4665-b70b-170d81704973)
![image](https://github.com/Mooooooon/TiezhuToolbox/assets/77432137/290872c4-ced6-4546-92c6-2e64e30f437c)
![image](https://github.com/Mooooooon/TiezhuToolbox/assets/77432137/515ecfc2-4ecb-488e-aa52-1a922641d5da)
![image](https://github.com/Mooooooon/TiezhuToolbox/assets/77432137/4848b0fc-86f4-44ad-a89c-3b1797d50fda)
![image](https://github.com/Mooooooon/TiezhuToolbox/assets/77432137/d941f987-f367-4945-bed1-db6b251c083d)
![image](https://github.com/Mooooooon/TiezhuToolbox/assets/77432137/19c3a5ac-796f-483a-ab29-2a9335836db0)
[都市之履.zip](https://github.com/Mooooooon/TiezhuToolbox/files/13854304/default.zip)
[上级倒下的英雄之短剑.zip](https://github.com/Mooooooon/TiezhuToolbox/files/13854305/default.zip)
[上级倒下的英雄之靴.zip](https://github.com/Mooooooon/TiezhuToolbox/files/13854306/default.zip)
[少女们的友情戒指.zip](https://github.com/Mooooooon/TiezhuToolbox/files/13854307/default.zip)
[野花胸针.zip](https://github.com/Mooooooon/TiezhuToolbox/files/13854308/default.zip)
[缘分信物.zip](https://github.com/Mooooooon/TiezhuToolbox/files/13854309/default.zip)

同一个前缀名的装备，例如上级之xxx，有的可以正常显示，有的不行。
temp图我也看到了，确实已经将无用的信息涂黑。

**Comment by Mooooooon** [comment]
原来是被过滤了，我设置的匹配度低于60%的过滤掉（主要是为了过滤重铸的🔁标志和紫装+12之前的🔒标志）
看来评分50%以上的结果应该是准确的
![QQ截图20240111010923](https://github.com/Mooooooon/TiezhuToolbox/assets/7168329/56c6788e-de7e-4f3e-be1e-2b8966216783)
（不知道这个5为什么评分这么低，怎么看都像一个普通的5）
下版本修复
