### ISSUE TITLE
背包紫装词条识别问题

### ISSUE THREAD

**Issue by hsj1992** [Mooooooon/TiezhuToolbox#4]
软件版本：1.0.2
在背包里识别不到第三条速度词条，打开强化界面才识别到。
附上temp里的图片。
背包状态：
![screenshot](https://github.com/Mooooooon/TiezhuToolbox/assets/4816005/7fa178ff-c2cf-4854-8aad-1f032f775b46)
![gear_info](https://github.com/Mooooooon/TiezhuToolbox/assets/4816005/be343b62-d561-4a05-9764-4b8f68a38e7f)
<img width="601" alt="屏幕截图 2024-01-13 112523" src="https://github.com/Mooooooon/TiezhuToolbox/assets/4816005/a95d7af9-ef43-4b8d-87f0-3908251e6551">
强化界面状态：
![screenshot](https://github.com/Mooooooon/TiezhuToolbox/assets/4816005/c827c44e-9a4d-4c71-9b14-7b47c9eff910)
![gear_info](https://github.com/Mooooooon/TiezhuToolbox/assets/4816005/24ff9590-6b59-4a4b-b33d-515bf44b161a)
<img width="597" alt="屏幕截图 2024-01-13 112747" src="https://github.com/Mooooooon/TiezhuToolbox/assets/4816005/6c483b64-1067-49a4-b70f-41c6577aa5cf">

**Comment by Mooooooon** [comment]
应该是打码导致的文字区域判断错误，已修复

![QQ截图20240115160534](https://github.com/Mooooooon/TiezhuToolbox/assets/7168329/493d9691-c589-42ca-b21f-359cdcc40594)
